class AddTreatmentCompletionVariablesToSubject < ActiveRecord::Migration
  def change
  	add_column :subjects, :tc_smfa_1, :integer
	add_column :subjects, :tc_smfa_2, :integer
	add_column :subjects, :tc_smfa_3, :integer
	add_column :subjects, :tc_smfa_4, :integer
	add_column :subjects, :tc_smfa_5, :integer
	add_column :subjects, :tc_smfa_6, :integer
	add_column :subjects, :tc_smfa_7, :integer
	add_column :subjects, :tc_smfa_8, :integer
	add_column :subjects, :tc_smfa_9, :integer
	add_column :subjects, :tc_smfa_10, :integer
	add_column :subjects, :tc_smfa_11, :integer
	add_column :subjects, :tc_smfa_12, :integer
	add_column :subjects, :tc_smfa_13, :integer
	add_column :subjects, :tc_smfa_14, :integer
	add_column :subjects, :tc_smfa_15, :integer
	add_column :subjects, :tc_smfa_16, :integer
	add_column :subjects, :tc_smfa_17, :integer
	add_column :subjects, :tc_smfa_18, :integer
	add_column :subjects, :tc_smfa_19, :integer
	add_column :subjects, :tc_smfa_20, :integer
	add_column :subjects, :tc_smfa_21, :integer
	add_column :subjects, :tc_smfa_22, :integer
	add_column :subjects, :tc_smfa_23, :integer
	add_column :subjects, :tc_smfa_24, :integer
	add_column :subjects, :tc_smfa_25, :integer
	add_column :subjects, :tc_smfa_26, :integer
	add_column :subjects, :tc_smfa_27, :integer
	add_column :subjects, :tc_smfa_28, :integer
	add_column :subjects, :tc_smfa_29, :integer
	add_column :subjects, :tc_smfa_30, :integer
	add_column :subjects, :tc_smfa_31, :integer
	add_column :subjects, :tc_smfa_32, :integer
	add_column :subjects, :tc_smfa_33, :integer
	add_column :subjects, :tc_smfa_34, :integer
	add_column :subjects, :tc_smfa_35, :integer
	add_column :subjects, :tc_smfa_36, :integer
	add_column :subjects, :tc_smfa_37, :integer
	add_column :subjects, :tc_smfa_38, :integer
	add_column :subjects, :tc_smfa_39, :integer
	add_column :subjects, :tc_smfa_40, :integer
	add_column :subjects, :tc_smfa_41, :integer
	add_column :subjects, :tc_smfa_42, :integer
	add_column :subjects, :tc_smfa_43, :integer
	add_column :subjects, :tc_smfa_44, :integer
	add_column :subjects, :tc_smfa_45, :integer
	add_column :subjects, :tc_smfa_46, :integer
	add_column :subjects, :tc_phq_1, :integer
	add_column :subjects, :tc_phq_2, :integer
	add_column :subjects, :tc_phq_3, :integer
	add_column :subjects, :tc_phq_4, :integer
	add_column :subjects, :tc_phq_5, :integer
	add_column :subjects, :tc_phq_6, :integer
	add_column :subjects, :tc_phq_7, :integer
	add_column :subjects, :tc_phq_8, :integer
	add_column :subjects, :tc_phq_9, :integer
	add_column :subjects, :tc_phq_10, :integer
	add_column :subjects, :tc_whoqol_1, :integer
	add_column :subjects, :tc_whoqol_2, :integer
	add_column :subjects, :tc_panas_1, :integer
	add_column :subjects, :tc_panas_2, :integer
	add_column :subjects, :tc_panas_3, :integer
	add_column :subjects, :tc_panas_4, :integer
	add_column :subjects, :tc_panas_5, :integer
	add_column :subjects, :tc_panas_6, :integer
	add_column :subjects, :tc_panas_7, :integer
	add_column :subjects, :tc_panas_8, :integer
	add_column :subjects, :tc_panas_9, :integer
	add_column :subjects, :tc_panas_10, :integer
	add_column :subjects, :tc_panas_11, :integer
	add_column :subjects, :tc_panas_12, :integer
	add_column :subjects, :tc_panas_13, :integer
	add_column :subjects, :tc_panas_14, :integer
	add_column :subjects, :tc_panas_15, :integer
	add_column :subjects, :tc_panas_16, :integer
	add_column :subjects, :tc_panas_17, :integer
	add_column :subjects, :tc_panas_18, :integer
	add_column :subjects, :tc_panas_19, :integer
	add_column :subjects, :tc_panas_20, :integer
	add_column :subjects, :tc_mses_1, :integer
	add_column :subjects, :tc_mses_2, :integer
	add_column :subjects, :tc_mses_3, :integer
	add_column :subjects, :tc_mses_4, :integer
	add_column :subjects, :tc_mses_5, :integer
	add_column :subjects, :tc_mses_6, :integer
	add_column :subjects, :tc_mses_7, :integer
	add_column :subjects, :tc_mses_8, :integer
	add_column :subjects, :tc_mses_9, :integer
	add_column :subjects, :tc_pam_1, :integer
	add_column :subjects, :tc_pam_2, :integer
	add_column :subjects, :tc_pam_3, :integer
	add_column :subjects, :tc_pam_4, :integer
	add_column :subjects, :tc_pam_5, :integer
	add_column :subjects, :tc_pam_6, :integer
	add_column :subjects, :tc_pam_7, :integer
	add_column :subjects, :tc_pam_8, :integer
	add_column :subjects, :tc_pam_9, :integer
	add_column :subjects, :tc_pam_10, :integer
	add_column :subjects, :tc_pam_11, :integer
	add_column :subjects, :tc_pam_12, :integer
	add_column :subjects, :tc_pam_13, :integer
	add_column :subjects, :tc_spsi_1, :integer
	add_column :subjects, :tc_spsi_2, :integer
	add_column :subjects, :tc_spsi_3, :integer
	add_column :subjects, :tc_spsi_4, :integer
	add_column :subjects, :tc_spsi_5, :integer
	add_column :subjects, :tc_spsi_6, :integer
	add_column :subjects, :tc_spsi_7, :integer
	add_column :subjects, :tc_spsi_8, :integer
	add_column :subjects, :tc_spsi_9, :integer
	add_column :subjects, :tc_spsi_10, :integer
	add_column :subjects, :tc_spsi_11, :integer
	add_column :subjects, :tc_spsi_12, :integer
	add_column :subjects, :tc_spsi_13, :integer
	add_column :subjects, :tc_spsi_14, :integer
	add_column :subjects, :tc_spsi_15, :integer
	add_column :subjects, :tc_spsi_16, :integer
	add_column :subjects, :tc_spsi_17, :integer
	add_column :subjects, :tc_spsi_18, :integer
	add_column :subjects, :tc_spsi_19, :integer
	add_column :subjects, :tc_spsi_20, :integer
	add_column :subjects, :tc_spsi_21, :integer
	add_column :subjects, :tc_spsi_22, :integer
	add_column :subjects, :tc_spsi_23, :integer
	add_column :subjects, :tc_spsi_24, :integer
	add_column :subjects, :tc_spsi_25, :integer
	add_column :subjects, :tc_soc_1, :integer
	add_column :subjects, :tc_soc_2, :integer
	add_column :subjects, :tc_soc_3, :integer
	add_column :subjects, :tc_soc_4, :integer
	add_column :subjects, :tc_soc_5, :integer
	add_column :subjects, :tc_soc_6, :integer
	add_column :subjects, :tc_pu_1, :integer
	add_column :subjects, :tc_pu_2, :integer
	add_column :subjects, :tc_pu_3, :integer
	add_column :subjects, :tc_pu_4, :integer
	add_column :subjects, :tc_cpg_1, :integer
	add_column :subjects, :tc_cpg_2, :integer
	add_column :subjects, :tc_cpg_3, :integer
	add_column :subjects, :tc_cpg_4, :integer
	add_column :subjects, :tc_cpg_5, :integer
	add_column :subjects, :tc_cpg_6, :integer
	add_column :subjects, :tc_cpg_7, :integer
	add_column :subjects, :tc_comp_1, :integer
	add_column :subjects, :tc_comp_2, :integer
	add_column :subjects, :tc_comp_3, :integer
	add_column :subjects, :tc_comp_4, :integer
	add_column :subjects, :tc_comp_5_a1, :integer
	add_column :subjects, :tc_comp_5_a2, :integer
	add_column :subjects, :tc_comp_5_a3, :integer
	add_column :subjects, :tc_comp_5_a4, :integer
	add_column :subjects, :tc_comp_5_a5, :integer
	add_column :subjects, :tc_comp_5_a6, :integer
	add_column :subjects, :tc_comp_5_a7, :integer
	add_column :subjects, :tc_comp_5b, :integer
	add_column :subjects, :tc_comp_5c, :integer
	add_column :subjects, :tc_comp_5c_level, :integer
	add_column :subjects, :tc_comp_5c_type, :integer
	add_column :subjects, :tc_mspss_1, :integer
	add_column :subjects, :tc_mspss_2, :integer
	add_column :subjects, :tc_mspss_3, :integer
	add_column :subjects, :tc_mspss_4, :integer
	add_column :subjects, :tc_mspss_5, :integer
	add_column :subjects, :tc_mspss_6, :integer
	add_column :subjects, :tc_mspss_7, :integer
	add_column :subjects, :tc_mspss_8, :integer
	add_column :subjects, :tc_mspss_9, :integer
	add_column :subjects, :tc_mspss_10, :integer
	add_column :subjects, :tc_mspss_11, :integer
	add_column :subjects, :tc_mspss_12, :integer
	add_column :subjects, :tc_audit_1, :integer
	add_column :subjects, :tc_audit_2, :integer
	add_column :subjects, :tc_audit_3, :integer
	add_column :subjects, :tc_ptcs_1, :integer
	add_column :subjects, :tc_ptcs_2, :integer
	add_column :subjects, :tc_ptcs_3, :integer
	add_column :subjects, :tc_ptcs_4, :integer
	add_column :subjects, :tc_ptcs_5, :integer
	add_column :subjects, :tc_ptcs_6, :integer
	add_column :subjects, :tc_ptcs_7, :integer
	add_column :subjects, :tc_ptcs_8, :integer
	add_column :subjects, :tc_ptcs_9, :integer
	add_column :subjects, :tc_ptcs_10, :integer
	add_column :subjects, :tc_ptcs_11, :integer
	add_column :subjects, :tc_ptcs_12, :integer
	add_column :subjects, :tc_ptcs_13, :integer
	add_column :subjects, :tc_ptcs_14, :integer
	add_column :subjects, :tc_ptcs_15, :integer
	add_column :subjects, :tc_ptcs_16, :integer
	add_column :subjects, :tc_ptcs_17, :integer
	add_column :subjects, :tc_ar_1, :integer
	add_column :subjects, :tc_ar_2, :integer
	add_column :subjects, :tc_ar_3, :integer
	add_column :subjects, :tc_ar_4, :integer
	add_column :subjects, :tc_ar_5, :integer
	add_column :subjects, :tc_ar_6, :integer
	add_column :subjects, :tc_ar_7, :integer
	add_column :subjects, :tc_ar_8, :integer
	add_column :subjects, :tc_ar_9, :integer
	add_column :subjects, :tc_ar_9o, :integer
	add_column :subjects, :tc_sat_1, :integer
	add_column :subjects, :tc_sat_2, :integer
	add_column :subjects, :tc_sat_3, :integer
	add_column :subjects, :tc_sat_4, :integer
	add_column :subjects, :tc_sat_5, :integer
	add_column :subjects, :tc_sat_6, :integer
	add_column :subjects, :tc_sat_7, :integer
	add_column :subjects, :tc_sat_8, :integer
	add_column :subjects, :tc_sat_9, :integer
	add_column :subjects, :tc_sat_10, :integer
	add_column :subjects, :tc_sat_11, :integer

  end
end
