class AddOtherFollowUpVariablesToSubject < ActiveRecord::Migration
  def change
  	add_column :subjects, :fu3week_fuq_1, :integer
	add_column :subjects, :fu3week_fuq_2, :integer
	add_column :subjects, :fu3week_fuq_2a, :integer
	add_column :subjects, :fu3week_fuq_3, :integer
	add_column :subjects, :fu3week_fuq_3a, :integer
	add_column :subjects, :fu3week_fuq_4, :integer
	add_column :subjects, :fu3week_fuq_4a_level, :integer
	add_column :subjects, :fu3week_fuq_4a_type, :integer
	add_column :subjects, :fu3week_fuq_4b, :integer
	add_column :subjects, :fu3week_fuq_5, :integer
	add_column :subjects, :fu3week_fuq_5a, :integer
	add_column :subjects, :fu3week_fuq_6, :integer
	add_column :subjects, :fu3week_fuq_6a, :integer
	add_column :subjects, :fu3week_fuq_7, :integer
	add_column :subjects, :fu6week_fuq_1, :integer
	add_column :subjects, :fu6week_fuq_2, :integer
	add_column :subjects, :fu6week_fuq_2a, :integer
	add_column :subjects, :fu6week_fuq_3, :integer
	add_column :subjects, :fu6week_fuq_3a, :integer
	add_column :subjects, :fu6week_fuq_4, :integer
	add_column :subjects, :fu6week_fuq_4a_level, :integer
	add_column :subjects, :fu6week_fuq_4a_type, :integer
	add_column :subjects, :fu6week_fuq_4b, :integer
	add_column :subjects, :fu6week_fuq_5, :integer
	add_column :subjects, :fu6week_fuq_5a, :integer
	add_column :subjects, :fu6week_fuq_6, :integer
	add_column :subjects, :fu6week_fuq_6a, :integer
	add_column :subjects, :fu6week_fuq_7, :integer
	add_column :subjects, :fu18week_fuq_1, :integer
	add_column :subjects, :fu18week_fuq_2, :integer
	add_column :subjects, :fu18week_fuq_2a, :integer
	add_column :subjects, :fu18week_fuq_3, :integer
	add_column :subjects, :fu18week_fuq_3a, :integer
	add_column :subjects, :fu18week_fuq_4, :integer
	add_column :subjects, :fu18week_fuq_4a_level, :integer
	add_column :subjects, :fu18week_fuq_4a_type, :integer
	add_column :subjects, :fu18week_fuq_4b, :integer
	add_column :subjects, :fu18week_fuq_5, :integer
	add_column :subjects, :fu18week_fuq_5a, :integer
	add_column :subjects, :fu18week_fuq_6, :integer
	add_column :subjects, :fu18week_fuq_6a, :integer
	add_column :subjects, :fu18week_fuq_7, :integer
	add_column :subjects, :fu1year_fuq_1, :integer
	add_column :subjects, :fu1year_fuq_2, :integer
	add_column :subjects, :fu1year_fuq_2a, :integer
	add_column :subjects, :fu1year_fuq_3, :integer
	add_column :subjects, :fu1year_fuq_3a, :integer
	add_column :subjects, :fu1year_fuq_4, :integer
	add_column :subjects, :fu1year_fuq_4a_level, :integer
	add_column :subjects, :fu1year_fuq_4a_type, :integer
	add_column :subjects, :fu1year_fuq_4b, :integer
	add_column :subjects, :fu1year_fuq_5, :integer
	add_column :subjects, :fu1year_fuq_5a, :integer
	add_column :subjects, :fu1year_fuq_6, :integer
	add_column :subjects, :fu1year_fuq_6a, :integer
	add_column :subjects, :fu1year_fuq_7, :integer

  end
end
