class Add6MonthFollowUpVariablesToSubject < ActiveRecord::Migration
  def change
  	add_column :subjects, :fu6month_smfa_1, :integer
	add_column :subjects, :fu6month_smfa_2, :integer
	add_column :subjects, :fu6month_smfa_3, :integer
	add_column :subjects, :fu6month_smfa_4, :integer
	add_column :subjects, :fu6month_smfa_5, :integer
	add_column :subjects, :fu6month_smfa_6, :integer
	add_column :subjects, :fu6month_smfa_7, :integer
	add_column :subjects, :fu6month_smfa_8, :integer
	add_column :subjects, :fu6month_smfa_9, :integer
	add_column :subjects, :fu6month_smfa_10, :integer
	add_column :subjects, :fu6month_smfa_11, :integer
	add_column :subjects, :fu6month_smfa_12, :integer
	add_column :subjects, :fu6month_smfa_13, :integer
	add_column :subjects, :fu6month_smfa_14, :integer
	add_column :subjects, :fu6month_smfa_15, :integer
	add_column :subjects, :fu6month_smfa_16, :integer
	add_column :subjects, :fu6month_smfa_17, :integer
	add_column :subjects, :fu6month_smfa_18, :integer
	add_column :subjects, :fu6month_smfa_19, :integer
	add_column :subjects, :fu6month_smfa_20, :integer
	add_column :subjects, :fu6month_smfa_21, :integer
	add_column :subjects, :fu6month_smfa_22, :integer
	add_column :subjects, :fu6month_smfa_23, :integer
	add_column :subjects, :fu6month_smfa_24, :integer
	add_column :subjects, :fu6month_smfa_25, :integer
	add_column :subjects, :fu6month_smfa_26, :integer
	add_column :subjects, :fu6month_smfa_27, :integer
	add_column :subjects, :fu6month_smfa_28, :integer
	add_column :subjects, :fu6month_smfa_29, :integer
	add_column :subjects, :fu6month_smfa_30, :integer
	add_column :subjects, :fu6month_smfa_31, :integer
	add_column :subjects, :fu6month_smfa_32, :integer
	add_column :subjects, :fu6month_smfa_33, :integer
	add_column :subjects, :fu6month_smfa_34, :integer
	add_column :subjects, :fu6month_smfa_35, :integer
	add_column :subjects, :fu6month_smfa_36, :integer
	add_column :subjects, :fu6month_smfa_37, :integer
	add_column :subjects, :fu6month_smfa_38, :integer
	add_column :subjects, :fu6month_smfa_39, :integer
	add_column :subjects, :fu6month_smfa_40, :integer
	add_column :subjects, :fu6month_smfa_41, :integer
	add_column :subjects, :fu6month_smfa_42, :integer
	add_column :subjects, :fu6month_smfa_43, :integer
	add_column :subjects, :fu6month_smfa_44, :integer
	add_column :subjects, :fu6month_smfa_45, :integer
	add_column :subjects, :fu6month_smfa_46, :integer
	add_column :subjects, :fu6month_phq_1, :integer
	add_column :subjects, :fu6month_phq_2, :integer
	add_column :subjects, :fu6month_phq_3, :integer
	add_column :subjects, :fu6month_phq_4, :integer
	add_column :subjects, :fu6month_phq_5, :integer
	add_column :subjects, :fu6month_phq_6, :integer
	add_column :subjects, :fu6month_phq_7, :integer
	add_column :subjects, :fu6month_phq_8, :integer
	add_column :subjects, :fu6month_phq_9, :integer
	add_column :subjects, :fu6month_phq_10, :integer
	add_column :subjects, :fu6month_whoqol_1, :integer
	add_column :subjects, :fu6month_whoqol_2, :integer
	add_column :subjects, :fu6month_panas_1, :integer
	add_column :subjects, :fu6month_panas_2, :integer
	add_column :subjects, :fu6month_panas_3, :integer
	add_column :subjects, :fu6month_panas_4, :integer
	add_column :subjects, :fu6month_panas_5, :integer
	add_column :subjects, :fu6month_panas_6, :integer
	add_column :subjects, :fu6month_panas_7, :integer
	add_column :subjects, :fu6month_panas_8, :integer
	add_column :subjects, :fu6month_panas_9, :integer
	add_column :subjects, :fu6month_panas_10, :integer
	add_column :subjects, :fu6month_panas_11, :integer
	add_column :subjects, :fu6month_panas_12, :integer
	add_column :subjects, :fu6month_panas_13, :integer
	add_column :subjects, :fu6month_panas_14, :integer
	add_column :subjects, :fu6month_panas_15, :integer
	add_column :subjects, :fu6month_panas_16, :integer
	add_column :subjects, :fu6month_panas_17, :integer
	add_column :subjects, :fu6month_panas_18, :integer
	add_column :subjects, :fu6month_panas_19, :integer
	add_column :subjects, :fu6month_panas_20, :integer
	add_column :subjects, :fu6month_mses_1, :integer
	add_column :subjects, :fu6month_mses_2, :integer
	add_column :subjects, :fu6month_mses_3, :integer
	add_column :subjects, :fu6month_mses_4, :integer
	add_column :subjects, :fu6month_mses_5, :integer
	add_column :subjects, :fu6month_mses_6, :integer
	add_column :subjects, :fu6month_mses_7, :integer
	add_column :subjects, :fu6month_mses_8, :integer
	add_column :subjects, :fu6month_mses_9, :integer
	add_column :subjects, :fu6month_pam_1, :integer
	add_column :subjects, :fu6month_pam_2, :integer
	add_column :subjects, :fu6month_pam_3, :integer
	add_column :subjects, :fu6month_pam_4, :integer
	add_column :subjects, :fu6month_pam_5, :integer
	add_column :subjects, :fu6month_pam_6, :integer
	add_column :subjects, :fu6month_pam_7, :integer
	add_column :subjects, :fu6month_pam_8, :integer
	add_column :subjects, :fu6month_pam_9, :integer
	add_column :subjects, :fu6month_pam_10, :integer
	add_column :subjects, :fu6month_pam_11, :integer
	add_column :subjects, :fu6month_pam_12, :integer
	add_column :subjects, :fu6month_pam_13, :integer
	add_column :subjects, :fu6month_spsi_1, :integer
	add_column :subjects, :fu6month_spsi_2, :integer
	add_column :subjects, :fu6month_spsi_3, :integer
	add_column :subjects, :fu6month_spsi_4, :integer
	add_column :subjects, :fu6month_spsi_5, :integer
	add_column :subjects, :fu6month_spsi_6, :integer
	add_column :subjects, :fu6month_spsi_7, :integer
	add_column :subjects, :fu6month_spsi_8, :integer
	add_column :subjects, :fu6month_spsi_9, :integer
	add_column :subjects, :fu6month_spsi_10, :integer
	add_column :subjects, :fu6month_spsi_11, :integer
	add_column :subjects, :fu6month_spsi_12, :integer
	add_column :subjects, :fu6month_spsi_13, :integer
	add_column :subjects, :fu6month_spsi_14, :integer
	add_column :subjects, :fu6month_spsi_15, :integer
	add_column :subjects, :fu6month_spsi_16, :integer
	add_column :subjects, :fu6month_spsi_17, :integer
	add_column :subjects, :fu6month_spsi_18, :integer
	add_column :subjects, :fu6month_spsi_19, :integer
	add_column :subjects, :fu6month_spsi_20, :integer
	add_column :subjects, :fu6month_spsi_21, :integer
	add_column :subjects, :fu6month_spsi_22, :integer
	add_column :subjects, :fu6month_spsi_23, :integer
	add_column :subjects, :fu6month_spsi_24, :integer
	add_column :subjects, :fu6month_spsi_25, :integer
	add_column :subjects, :fu6month_soc_1, :integer
	add_column :subjects, :fu6month_soc_2, :integer
	add_column :subjects, :fu6month_soc_3, :integer
	add_column :subjects, :fu6month_soc_4, :integer
	add_column :subjects, :fu6month_soc_5, :integer
	add_column :subjects, :fu6month_soc_6, :integer
	add_column :subjects, :fu6month_pu_1, :integer
	add_column :subjects, :fu6month_pu_2, :integer
	add_column :subjects, :fu6month_pu_3, :integer
	add_column :subjects, :fu6month_pu_4, :integer
	add_column :subjects, :fu6month_cpg_1, :integer
	add_column :subjects, :fu6month_cpg_2, :integer
	add_column :subjects, :fu6month_cpg_3, :integer
	add_column :subjects, :fu6month_cpg_4, :integer
	add_column :subjects, :fu6month_cpg_5, :integer
	add_column :subjects, :fu6month_cpg_6, :integer
	add_column :subjects, :fu6month_cpg_7, :integer
	add_column :subjects, :fu6month_comp_1, :integer
	add_column :subjects, :fu6month_comp_2, :integer
	add_column :subjects, :fu6month_comp_3, :integer
	add_column :subjects, :fu6month_comp_4, :integer
	add_column :subjects, :fu6month_comp_5_a1, :integer
	add_column :subjects, :fu6month_comp_5_a2, :integer
	add_column :subjects, :fu6month_comp_5_a3, :integer
	add_column :subjects, :fu6month_comp_5_a4, :integer
	add_column :subjects, :fu6month_comp_5_a5, :integer
	add_column :subjects, :fu6month_comp_5_a6, :integer
	add_column :subjects, :fu6month_comp_5_a7, :integer
	add_column :subjects, :fu6month_comp_5b, :integer
	add_column :subjects, :fu6month_comp_5c, :integer
	add_column :subjects, :fu6month_comp_5c_level, :integer
	add_column :subjects, :fu6month_comp_5c_type, :integer
	add_column :subjects, :fu6month_mspss_1, :integer
	add_column :subjects, :fu6month_mspss_2, :integer
	add_column :subjects, :fu6month_mspss_3, :integer
	add_column :subjects, :fu6month_mspss_4, :integer
	add_column :subjects, :fu6month_mspss_5, :integer
	add_column :subjects, :fu6month_mspss_6, :integer
	add_column :subjects, :fu6month_mspss_7, :integer
	add_column :subjects, :fu6month_mspss_8, :integer
	add_column :subjects, :fu6month_mspss_9, :integer
	add_column :subjects, :fu6month_mspss_10, :integer
	add_column :subjects, :fu6month_mspss_11, :integer
	add_column :subjects, :fu6month_mspss_12, :integer
	add_column :subjects, :fu6month_audit_1, :integer
	add_column :subjects, :fu6month_audit_2, :integer
	add_column :subjects, :fu6month_audit_3, :integer
  end
end
