class AddControlledWordAssociationVariablesToBaselines < ActiveRecord::Migration
  def change
  	add_column :baselines, :base_cowat_f, :integer
  	add_column :baselines, :base_cowat_a, :integer
  	add_column :baselines, :base_cowat_s, :integer
  	add_column :baselines, :base_cowat_f_1, :string
  	add_column :baselines, :base_cowat_f_2, :string
  	add_column :baselines, :base_cowat_f_3, :string
  	add_column :baselines, :base_cowat_f_4, :string
  	add_column :baselines, :base_cowat_f_5, :string
  	add_column :baselines, :base_cowat_f_6, :string
  	add_column :baselines, :base_cowat_f_7, :string
  	add_column :baselines, :base_cowat_f_8, :string
  	add_column :baselines, :base_cowat_f_9, :string
  	add_column :baselines, :base_cowat_f_10, :string
  	add_column :baselines, :base_cowat_f_11, :string
  	add_column :baselines, :base_cowat_f_12, :string
  	add_column :baselines, :base_cowat_f_13, :string
  	add_column :baselines, :base_cowat_f_14, :string
  	add_column :baselines, :base_cowat_f_15, :string
  	add_column :baselines, :base_cowat_f_16, :string
  	add_column :baselines, :base_cowat_f_17, :string
  	add_column :baselines, :base_cowat_f_18, :string
  	add_column :baselines, :base_cowat_f_19, :string
  	add_column :baselines, :base_cowat_f_20, :string
  	add_column :baselines, :base_cowat_f_21, :string
  	add_column :baselines, :base_cowat_f_22, :string
  	add_column :baselines, :base_cowat_f_23, :string
  	add_column :baselines, :base_cowat_f_24, :string
  	add_column :baselines, :base_cowat_f_25, :string
  	add_column :baselines, :base_cowat_a_1, :string
  	add_column :baselines, :base_cowat_a_2, :string
  	add_column :baselines, :base_cowat_a_3, :string
  	add_column :baselines, :base_cowat_a_4, :string
  	add_column :baselines, :base_cowat_a_5, :string
  	add_column :baselines, :base_cowat_a_6, :string
  	add_column :baselines, :base_cowat_a_7, :string
  	add_column :baselines, :base_cowat_a_8, :string
  	add_column :baselines, :base_cowat_a_9, :string
  	add_column :baselines, :base_cowat_a_10, :string
  	add_column :baselines, :base_cowat_a_11, :string
  	add_column :baselines, :base_cowat_a_12, :string
  	add_column :baselines, :base_cowat_a_13, :string
  	add_column :baselines, :base_cowat_a_14, :string
  	add_column :baselines, :base_cowat_a_15, :string
  	add_column :baselines, :base_cowat_a_16, :string
  	add_column :baselines, :base_cowat_a_17, :string
  	add_column :baselines, :base_cowat_a_18, :string
  	add_column :baselines, :base_cowat_a_19, :string
  	add_column :baselines, :base_cowat_a_20, :string
  	add_column :baselines, :base_cowat_a_21, :string
  	add_column :baselines, :base_cowat_a_22, :string
  	add_column :baselines, :base_cowat_a_23, :string
  	add_column :baselines, :base_cowat_a_24, :string
  	add_column :baselines, :base_cowat_a_25, :string
  	add_column :baselines, :base_cowat_s_1, :string
  	add_column :baselines, :base_cowat_s_2, :string
  	add_column :baselines, :base_cowat_s_3, :string
  	add_column :baselines, :base_cowat_s_4, :string
  	add_column :baselines, :base_cowat_s_5, :string
  	add_column :baselines, :base_cowat_s_6, :string
  	add_column :baselines, :base_cowat_s_7, :string
  	add_column :baselines, :base_cowat_s_8, :string
  	add_column :baselines, :base_cowat_s_9, :string
  	add_column :baselines, :base_cowat_s_10, :string
  	add_column :baselines, :base_cowat_s_11, :string
  	add_column :baselines, :base_cowat_s_12, :string
  	add_column :baselines, :base_cowat_s_13, :string
  	add_column :baselines, :base_cowat_s_14, :string
  	add_column :baselines, :base_cowat_s_15, :string
  	add_column :baselines, :base_cowat_s_16, :string
  	add_column :baselines, :base_cowat_s_17, :string
  	add_column :baselines, :base_cowat_s_18, :string
  	add_column :baselines, :base_cowat_s_19, :string
  	add_column :baselines, :base_cowat_s_20, :string
  	add_column :baselines, :base_cowat_s_21, :string
  	add_column :baselines, :base_cowat_s_22, :string
  	add_column :baselines, :base_cowat_s_23, :string
  	add_column :baselines, :base_cowat_s_24, :string
  	add_column :baselines, :base_cowat_s_25, :string
  end
end
