class CreateTreatmentCompletions < ActiveRecord::Migration
  def change
    create_table :treatment_completions do |t|
      	t.integer :subject_id
      	t.belongs_to :subject
      	t.integer :tc_smfa_1
		t.integer :tc_smfa_2
		t.integer :tc_smfa_3
		t.integer :tc_smfa_4
		t.integer :tc_smfa_5
		t.integer :tc_smfa_6
		t.integer :tc_smfa_7
		t.integer :tc_smfa_8
		t.integer :tc_smfa_9
		t.integer :tc_smfa_10
		t.integer :tc_smfa_11
		t.integer :tc_smfa_12
		t.integer :tc_smfa_13
		t.integer :tc_smfa_14
		t.integer :tc_smfa_15
		t.integer :tc_smfa_16
		t.integer :tc_smfa_17
		t.integer :tc_smfa_18
		t.integer :tc_smfa_19
		t.integer :tc_smfa_20
		t.integer :tc_smfa_21
		t.integer :tc_smfa_22
		t.integer :tc_smfa_23
		t.integer :tc_smfa_24
		t.integer :tc_smfa_25
		t.integer :tc_smfa_26
		t.integer :tc_smfa_27
		t.integer :tc_smfa_28
		t.integer :tc_smfa_29
		t.integer :tc_smfa_30
		t.integer :tc_smfa_31
		t.integer :tc_smfa_32
		t.integer :tc_smfa_33
		t.integer :tc_smfa_34
		t.integer :tc_smfa_35
		t.integer :tc_smfa_36
		t.integer :tc_smfa_37
		t.integer :tc_smfa_38
		t.integer :tc_smfa_39
		t.integer :tc_smfa_40
		t.integer :tc_smfa_41
		t.integer :tc_smfa_42
		t.integer :tc_smfa_43
		t.integer :tc_smfa_44
		t.integer :tc_smfa_45
		t.integer :tc_smfa_46
		t.integer :tc_phq_1
		t.integer :tc_phq_2
		t.integer :tc_phq_3
		t.integer :tc_phq_4
		t.integer :tc_phq_5
		t.integer :tc_phq_6
		t.integer :tc_phq_7
		t.integer :tc_phq_8
		t.integer :tc_phq_9
		t.integer :tc_phq_10
		t.integer :tc_whoqol_1
		t.integer :tc_whoqol_2
		t.integer :tc_panas_1
		t.integer :tc_panas_2
		t.integer :tc_panas_3
		t.integer :tc_panas_4
		t.integer :tc_panas_5
		t.integer :tc_panas_6
		t.integer :tc_panas_7
		t.integer :tc_panas_8
		t.integer :tc_panas_9
		t.integer :tc_panas_10
		t.integer :tc_panas_11
		t.integer :tc_panas_12
		t.integer :tc_panas_13
		t.integer :tc_panas_14
		t.integer :tc_panas_15
		t.integer :tc_panas_16
		t.integer :tc_panas_17
		t.integer :tc_panas_18
		t.integer :tc_panas_19
		t.integer :tc_panas_20
		t.integer :tc_mses_1
		t.integer :tc_mses_2
		t.integer :tc_mses_3
		t.integer :tc_mses_4
		t.integer :tc_mses_5
		t.integer :tc_mses_6
		t.integer :tc_mses_7
		t.integer :tc_mses_8
		t.integer :tc_mses_9
		t.integer :tc_pam_1
		t.integer :tc_pam_2
		t.integer :tc_pam_3
		t.integer :tc_pam_4
		t.integer :tc_pam_5
		t.integer :tc_pam_6
		t.integer :tc_pam_7
		t.integer :tc_pam_8
		t.integer :tc_pam_9
		t.integer :tc_pam_10
		t.integer :tc_pam_11
		t.integer :tc_pam_12
		t.integer :tc_pam_13
		t.integer :tc_spsi_1
		t.integer :tc_spsi_2
		t.integer :tc_spsi_3
		t.integer :tc_spsi_4
		t.integer :tc_spsi_5
		t.integer :tc_spsi_6
		t.integer :tc_spsi_7
		t.integer :tc_spsi_8
		t.integer :tc_spsi_9
		t.integer :tc_spsi_10
		t.integer :tc_spsi_11
		t.integer :tc_spsi_12
		t.integer :tc_spsi_13
		t.integer :tc_spsi_14
		t.integer :tc_spsi_15
		t.integer :tc_spsi_16
		t.integer :tc_spsi_17
		t.integer :tc_spsi_18
		t.integer :tc_spsi_19
		t.integer :tc_spsi_20
		t.integer :tc_spsi_21
		t.integer :tc_spsi_22
		t.integer :tc_spsi_23
		t.integer :tc_spsi_24
		t.integer :tc_spsi_25
		t.integer :tc_soc_1
		t.integer :tc_soc_2
		t.integer :tc_soc_3
		t.integer :tc_soc_4
		t.integer :tc_soc_5
		t.integer :tc_soc_6
		t.integer :tc_pu_1
		t.integer :tc_pu_2
		t.integer :tc_pu_3
		t.integer :tc_pu_4
		t.integer :tc_cpg_1
		t.integer :tc_cpg_2
		t.integer :tc_cpg_3
		t.integer :tc_cpg_4
		t.integer :tc_cpg_5
		t.integer :tc_cpg_6
		t.integer :tc_cpg_7
		t.integer :tc_comp_1
		t.integer :tc_comp_2
		t.integer :tc_comp_3
		t.integer :tc_comp_4
		t.integer :tc_comp_5_a1
		t.integer :tc_comp_5_a2
		t.integer :tc_comp_5_a3
		t.integer :tc_comp_5_a4
		t.integer :tc_comp_5_a5
		t.integer :tc_comp_5_a6
		t.integer :tc_comp_5_a7
		t.integer :tc_comp_5b
		t.integer :tc_comp_5c
		t.integer :tc_comp_5c_level
		t.integer :tc_comp_5c_type
		t.integer :tc_mspss_1
		t.integer :tc_mspss_2
		t.integer :tc_mspss_3
		t.integer :tc_mspss_4
		t.integer :tc_mspss_5
		t.integer :tc_mspss_6
		t.integer :tc_mspss_7
		t.integer :tc_mspss_8
		t.integer :tc_mspss_9
		t.integer :tc_mspss_10
		t.integer :tc_mspss_11
		t.integer :tc_mspss_12
		t.integer :tc_audit_1
		t.integer :tc_audit_2
		t.integer :tc_audit_3
		t.integer :tc_ptcs_1
		t.integer :tc_ptcs_2
		t.integer :tc_ptcs_3
		t.integer :tc_ptcs_4
		t.integer :tc_ptcs_5
		t.integer :tc_ptcs_6
		t.integer :tc_ptcs_7
		t.integer :tc_ptcs_8
		t.integer :tc_ptcs_9
		t.integer :tc_ptcs_10
		t.integer :tc_ptcs_11
		t.integer :tc_ptcs_12
		t.integer :tc_ptcs_13
		t.integer :tc_ptcs_14
		t.integer :tc_ptcs_15
		t.integer :tc_ptcs_16
		t.integer :tc_ptcs_17
		t.integer :tc_ar_1
		t.integer :tc_ar_2
		t.integer :tc_ar_3
		t.integer :tc_ar_4
		t.integer :tc_ar_5
		t.integer :tc_ar_6
		t.integer :tc_ar_7
		t.integer :tc_ar_8
		t.integer :tc_ar_9
		t.integer :tc_ar_9o
		t.integer :tc_sat_1
		t.integer :tc_sat_2
		t.integer :tc_sat_3
		t.integer :tc_sat_4
		t.integer :tc_sat_5
		t.integer :tc_sat_6
		t.integer :tc_sat_7
		t.integer :tc_sat_8
		t.integer :tc_sat_9
		t.integer :tc_sat_10
		t.integer :tc_sat_11
		t.references :subject

      	t.timestamps
    end
    add_index :treatment_completions, :subject_id
  end
end
