class RemoveColumns < ActiveRecord::Migration
  def up
  	remove_column :subjects, :base_smfa_1
	remove_column :subjects, :base_smfa_2
    remove_column :subjects, :base_smfa_3
    remove_column :subjects, :base_smfa_4
    remove_column :subjects, :base_smfa_5
    remove_column :subjects, :base_smfa_6
    remove_column :subjects, :base_smfa_7
    remove_column :subjects, :base_smfa_8
    remove_column :subjects, :base_smfa_9
    remove_column :subjects, :base_smfa_10
    remove_column :subjects, :base_smfa_11
    remove_column :subjects, :base_smfa_12
    remove_column :subjects, :base_smfa_13
    remove_column :subjects, :base_smfa_14
    remove_column :subjects, :base_smfa_15
    remove_column :subjects, :base_smfa_16
    remove_column :subjects, :base_smfa_17
    remove_column :subjects, :base_smfa_18
    remove_column :subjects, :base_smfa_19
    remove_column :subjects, :base_smfa_20
    remove_column :subjects, :base_smfa_21
    remove_column :subjects, :base_smfa_22
    remove_column :subjects, :base_smfa_23
    remove_column :subjects, :base_smfa_24
    remove_column :subjects, :base_smfa_25
    remove_column :subjects, :base_smfa_26
    remove_column :subjects, :base_smfa_27
    remove_column :subjects, :base_smfa_28
    remove_column :subjects, :base_smfa_29
    remove_column :subjects, :base_smfa_30
    remove_column :subjects, :base_smfa_31
    remove_column :subjects, :base_smfa_32
    remove_column :subjects, :base_smfa_33
    remove_column :subjects, :base_smfa_34
    remove_column :subjects, :base_smfa_35
    remove_column :subjects, :base_smfa_36
    remove_column :subjects, :base_smfa_37
    remove_column :subjects, :base_smfa_38
    remove_column :subjects, :base_smfa_39
    remove_column :subjects, :base_smfa_40
    remove_column :subjects, :base_smfa_41
    remove_column :subjects, :base_smfa_42
    remove_column :subjects, :base_smfa_43
    remove_column :subjects, :base_smfa_44
    remove_column :subjects, :base_smfa_45
    remove_column :subjects, :base_smfa_46
    remove_column :subjects, :base_phq_1
    remove_column :subjects, :base_phq_2
    remove_column :subjects, :base_phq_3
    remove_column :subjects, :base_phq_4
    remove_column :subjects, :base_phq_5
    remove_column :subjects, :base_phq_6
    remove_column :subjects, :base_phq_7
    remove_column :subjects, :base_phq_8
    remove_column :subjects, :base_phq_9
    remove_column :subjects, :base_phq_10
    remove_column :subjects, :base_whoqol_1
    remove_column :subjects, :base_whoqol_2
    remove_column :subjects, :base_panas_1
    remove_column :subjects, :base_panas_2
    remove_column :subjects, :base_panas_3
    remove_column :subjects, :base_panas_4
    remove_column :subjects, :base_panas_5
    remove_column :subjects, :base_panas_6
    remove_column :subjects, :base_panas_7
    remove_column :subjects, :base_panas_8
    remove_column :subjects, :base_panas_9
    remove_column :subjects, :base_panas_10
    remove_column :subjects, :base_panas_11
    remove_column :subjects, :base_panas_12
    remove_column :subjects, :base_panas_13
    remove_column :subjects, :base_panas_14
    remove_column :subjects, :base_panas_15
    remove_column :subjects, :base_panas_16
    remove_column :subjects, :base_panas_17
    remove_column :subjects, :base_panas_18
    remove_column :subjects, :base_panas_19
    remove_column :subjects, :base_panas_20
    remove_column :subjects, :base_mses_1
    remove_column :subjects, :base_mses_2
    remove_column :subjects, :base_mses_3
    remove_column :subjects, :base_mses_4
    remove_column :subjects, :base_mses_5
    remove_column :subjects, :base_mses_6
    remove_column :subjects, :base_mses_7
    remove_column :subjects, :base_mses_8
    remove_column :subjects, :base_mses_9
    remove_column :subjects, :base_pam_1
    remove_column :subjects, :base_pam_2
    remove_column :subjects, :base_pam_3
    remove_column :subjects, :base_pam_4
    remove_column :subjects, :base_pam_5
    remove_column :subjects, :base_pam_6
    remove_column :subjects, :base_pam_7
    remove_column :subjects, :base_pam_8
    remove_column :subjects, :base_pam_9
    remove_column :subjects, :base_pam_10
    remove_column :subjects, :base_pam_11
    remove_column :subjects, :base_pam_12
    remove_column :subjects, :base_pam_13
    remove_column :subjects, :base_spsi_1
    remove_column :subjects, :base_spsi_2
    remove_column :subjects, :base_spsi_3
    remove_column :subjects, :base_spsi_4
    remove_column :subjects, :base_spsi_5
    remove_column :subjects, :base_spsi_6
    remove_column :subjects, :base_spsi_7
    remove_column :subjects, :base_spsi_8
    remove_column :subjects, :base_spsi_9
    remove_column :subjects, :base_spsi_10
    remove_column :subjects, :base_spsi_11
    remove_column :subjects, :base_spsi_12
    remove_column :subjects, :base_spsi_13
    remove_column :subjects, :base_spsi_14
    remove_column :subjects, :base_spsi_15
    remove_column :subjects, :base_spsi_16
    remove_column :subjects, :base_spsi_17
    remove_column :subjects, :base_spsi_18
    remove_column :subjects, :base_spsi_19
    remove_column :subjects, :base_spsi_20
    remove_column :subjects, :base_spsi_21
    remove_column :subjects, :base_spsi_22
    remove_column :subjects, :base_spsi_23
    remove_column :subjects, :base_spsi_24
    remove_column :subjects, :base_spsi_25
    remove_column :subjects, :base_soc_1
    remove_column :subjects, :base_soc_2
    remove_column :subjects, :base_soc_3
    remove_column :subjects, :base_soc_4
    remove_column :subjects, :base_soc_5
    remove_column :subjects, :base_soc_6
    remove_column :subjects, :base_pu_1
    remove_column :subjects, :base_pu_2
    remove_column :subjects, :base_pu_3
    remove_column :subjects, :base_pu_4
    remove_column :subjects, :base_rbans_t1_1
    remove_column :subjects, :base_rbans_t1_2
    remove_column :subjects, :base_rbans_t1_3
    remove_column :subjects, :base_rbans_t1_4
    remove_column :subjects, :base_rbans_t1_5
    remove_column :subjects, :base_rbans_t1_6
    remove_column :subjects, :base_rbans_t1_7
    remove_column :subjects, :base_rbans_t1_8
    remove_column :subjects, :base_rbans_t1_9
    remove_column :subjects, :base_rbans_t1_10    
    remove_column :subjects, :base_rbans_t2_1
    remove_column :subjects, :base_rbans_t2_2
    remove_column :subjects, :base_rbans_t2_3
    remove_column :subjects, :base_rbans_t2_4
    remove_column :subjects, :base_rbans_t2_5
    remove_column :subjects, :base_rbans_t2_6
    remove_column :subjects, :base_rbans_t2_7
    remove_column :subjects, :base_rbans_t2_8
    remove_column :subjects, :base_rbans_t2_9
    remove_column :subjects, :base_rbans_t2_10
    remove_column :subjects, :base_rbans_t3_1
    remove_column :subjects, :base_rbans_t3_2
    remove_column :subjects, :base_rbans_t3_3
    remove_column :subjects, :base_rbans_t3_4
    remove_column :subjects, :base_rbans_t3_5
    remove_column :subjects, :base_rbans_t3_6
    remove_column :subjects, :base_rbans_t3_7
    remove_column :subjects, :base_rbans_t3_8
    remove_column :subjects, :base_rbans_t3_9
    remove_column :subjects, :base_rbans_t3_10
    remove_column :subjects, :base_rbans_t4_1
    remove_column :subjects, :base_rbans_t4_2
    remove_column :subjects, :base_rbans_t4_3
    remove_column :subjects, :base_rbans_t4_4
    remove_column :subjects, :base_rbans_t4_5
    remove_column :subjects, :base_rbans_t4_6
    remove_column :subjects, :base_rbans_t4_7
    remove_column :subjects, :base_rbans_t4_8
    remove_column :subjects, :base_rbans_t4_9
    remove_column :subjects, :base_rbans_t4_10
    remove_column :subjects, :base_wais_a_1_t1
    remove_column :subjects, :base_wais_a_1_t2
    remove_column :subjects, :base_wais_a_2_t1
    remove_column :subjects, :base_wais_a_2_t2
    remove_column :subjects, :base_wais_a_3_t1
    remove_column :subjects, :base_wais_a_3_t2
    remove_column :subjects, :base_wais_a_4_t1
    remove_column :subjects, :base_wais_a_4_t2
    remove_column :subjects, :base_wais_a_5_t1
    remove_column :subjects, :base_wais_a_5_t2
    remove_column :subjects, :base_wais_a_6_t1
    remove_column :subjects, :base_wais_a_6_t2
    remove_column :subjects, :base_wais_a_7_t1
    remove_column :subjects, :base_wais_a_7_t2
    remove_column :subjects, :base_wais_a_8_t1
    remove_column :subjects, :base_wais_a_8_t2    
    remove_column :subjects, :base_wais_b_1_t1
    remove_column :subjects, :base_wais_b_1_t2
    remove_column :subjects, :base_wais_b_2_t1
    remove_column :subjects, :base_wais_b_2_t2
    remove_column :subjects, :base_wais_b_3_t1
    remove_column :subjects, :base_wais_b_3_t2
    remove_column :subjects, :base_wais_b_4_t1
    remove_column :subjects, :base_wais_b_4_t2
    remove_column :subjects, :base_wais_b_5_t1
    remove_column :subjects, :base_wais_b_5_t2
    remove_column :subjects, :base_wais_b_6_t1
    remove_column :subjects, :base_wais_b_6_t2
    remove_column :subjects, :base_wais_b_7_t1
    remove_column :subjects, :base_wais_b_7_t2
    remove_column :subjects, :base_rbans_re_1
    remove_column :subjects, :base_rbans_re_2
    remove_column :subjects, :base_rbans_re_3
    remove_column :subjects, :base_rbans_re_4
    remove_column :subjects, :base_rbans_re_5
    remove_column :subjects, :base_rbans_re_6
    remove_column :subjects, :base_rbans_re_7
    remove_column :subjects, :base_rbans_re_8
    remove_column :subjects, :base_rbans_re_9
    remove_column :subjects, :base_rbans_re_10
    remove_column :subjects, :base_cq_1a
    remove_column :subjects, :base_cq_1b
    remove_column :subjects, :base_cq_1b_side
    remove_column :subjects, :base_cq_1c
    remove_column :subjects, :base_cq_1d
    remove_column :subjects, :base_cq_1d_joint
    remove_column :subjects, :base_cq_1e
    remove_column :subjects, :base_cq_1f
    remove_column :subjects, :base_cq_1g
    remove_column :subjects, :base_cq_2
    remove_column :subjects, :base_cq_2a
    remove_column :subjects, :base_cq_3a
    remove_column :subjects, :base_cq_3b
    remove_column :subjects, :base_cq_3c
    remove_column :subjects, :base_cq_3d
    remove_column :subjects, :base_cq_4
    remove_column :subjects, :base_cq_5
    remove_column :subjects, :base_cq_6
    remove_column :subjects, :base_cq_7
    remove_column :subjects, :base_cq_8
    remove_column :subjects, :base_cq_9
    remove_column :subjects, :base_cq_10_a1
    remove_column :subjects, :base_cq_10_a2
    remove_column :subjects, :base_cq_10_a3
    remove_column :subjects, :base_cq_10_a4
    remove_column :subjects, :base_cq_10_a5
    remove_column :subjects, :base_cq_10_a6
    remove_column :subjects, :base_cq_10_a7
    remove_column :subjects, :base_cq_10_b
    remove_column :subjects, :base_cq_10_c
    remove_column :subjects, :base_cq_10_c_level
    remove_column :subjects, :base_cq_10_c_type
    remove_column :subjects, :base_cpg_1
    remove_column :subjects, :base_cpg_2
    remove_column :subjects, :base_cpg_3
    remove_column :subjects, :base_cpg_4
    remove_column :subjects, :base_cpg_5
    remove_column :subjects, :base_cpg_6
    remove_column :subjects, :base_cpg_7
    remove_column :subjects, :base_comp1
    remove_column :subjects, :base_comp2
    remove_column :subjects, :base_comp3
    remove_column :subjects, :base_comp4
    remove_column :subjects, :base_comp5_a1
    remove_column :subjects, :base_comp5_a2
    remove_column :subjects, :base_comp5_a3
    remove_column :subjects, :base_comp5_a4
    remove_column :subjects, :base_comp5_a5
    remove_column :subjects, :base_comp5_a6
    remove_column :subjects, :base_comp5_a7
    remove_column :subjects, :base_comp5b
    remove_column :subjects, :base_comp5c
    remove_column :subjects, :base_comp5c_level
    remove_column :subjects, :base_comp5c_type
    remove_column :subjects, :base_mspss_1
    remove_column :subjects, :base_mspss_2
    remove_column :subjects, :base_mspss_3
    remove_column :subjects, :base_mspss_4
    remove_column :subjects, :base_mspss_5
    remove_column :subjects, :base_mspss_6
    remove_column :subjects, :base_mspss_7
    remove_column :subjects, :base_mspss_8
    remove_column :subjects, :base_mspss_9
    remove_column :subjects, :base_mspss_10
    remove_column :subjects, :base_mspss_11
    remove_column :subjects, :base_mspss_12
    remove_column :subjects, :base_audit_1
    remove_column :subjects, :base_audit_2
    remove_column :subjects, :base_audit_3

  	remove_column :subjects, :tc_smfa_1
	remove_column :subjects, :tc_smfa_2
	remove_column :subjects, :tc_smfa_3
	remove_column :subjects, :tc_smfa_4
	remove_column :subjects, :tc_smfa_5
	remove_column :subjects, :tc_smfa_6
	remove_column :subjects, :tc_smfa_7
	remove_column :subjects, :tc_smfa_8
	remove_column :subjects, :tc_smfa_9
	remove_column :subjects, :tc_smfa_10
	remove_column :subjects, :tc_smfa_11
	remove_column :subjects, :tc_smfa_12
	remove_column :subjects, :tc_smfa_13
	remove_column :subjects, :tc_smfa_14
	remove_column :subjects, :tc_smfa_15
	remove_column :subjects, :tc_smfa_16
	remove_column :subjects, :tc_smfa_17
	remove_column :subjects, :tc_smfa_18
	remove_column :subjects, :tc_smfa_19
	remove_column :subjects, :tc_smfa_20
	remove_column :subjects, :tc_smfa_21
	remove_column :subjects, :tc_smfa_22
	remove_column :subjects, :tc_smfa_23
	remove_column :subjects, :tc_smfa_24
	remove_column :subjects, :tc_smfa_25
	remove_column :subjects, :tc_smfa_26
	remove_column :subjects, :tc_smfa_27
	remove_column :subjects, :tc_smfa_28
	remove_column :subjects, :tc_smfa_29
	remove_column :subjects, :tc_smfa_30
	remove_column :subjects, :tc_smfa_31
	remove_column :subjects, :tc_smfa_32
	remove_column :subjects, :tc_smfa_33
	remove_column :subjects, :tc_smfa_34
	remove_column :subjects, :tc_smfa_35
	remove_column :subjects, :tc_smfa_36
	remove_column :subjects, :tc_smfa_37
	remove_column :subjects, :tc_smfa_38
	remove_column :subjects, :tc_smfa_39
	remove_column :subjects, :tc_smfa_40
	remove_column :subjects, :tc_smfa_41
	remove_column :subjects, :tc_smfa_42
	remove_column :subjects, :tc_smfa_43
	remove_column :subjects, :tc_smfa_44
	remove_column :subjects, :tc_smfa_45
	remove_column :subjects, :tc_smfa_46
	remove_column :subjects, :tc_phq_1
	remove_column :subjects, :tc_phq_2
	remove_column :subjects, :tc_phq_3
	remove_column :subjects, :tc_phq_4
	remove_column :subjects, :tc_phq_5
	remove_column :subjects, :tc_phq_6
	remove_column :subjects, :tc_phq_7
	remove_column :subjects, :tc_phq_8
	remove_column :subjects, :tc_phq_9
	remove_column :subjects, :tc_phq_10
	remove_column :subjects, :tc_whoqol_1
	remove_column :subjects, :tc_whoqol_2
	remove_column :subjects, :tc_panas_1
	remove_column :subjects, :tc_panas_2
	remove_column :subjects, :tc_panas_3
	remove_column :subjects, :tc_panas_4
	remove_column :subjects, :tc_panas_5
	remove_column :subjects, :tc_panas_6
	remove_column :subjects, :tc_panas_7
	remove_column :subjects, :tc_panas_8
	remove_column :subjects, :tc_panas_9
	remove_column :subjects, :tc_panas_10
	remove_column :subjects, :tc_panas_11
	remove_column :subjects, :tc_panas_12
	remove_column :subjects, :tc_panas_13
	remove_column :subjects, :tc_panas_14
	remove_column :subjects, :tc_panas_15
	remove_column :subjects, :tc_panas_16
	remove_column :subjects, :tc_panas_17
	remove_column :subjects, :tc_panas_18
	remove_column :subjects, :tc_panas_19
	remove_column :subjects, :tc_panas_20
	remove_column :subjects, :tc_mses_1
	remove_column :subjects, :tc_mses_2
	remove_column :subjects, :tc_mses_3
	remove_column :subjects, :tc_mses_4
	remove_column :subjects, :tc_mses_5
	remove_column :subjects, :tc_mses_6
	remove_column :subjects, :tc_mses_7
	remove_column :subjects, :tc_mses_8
	remove_column :subjects, :tc_mses_9
	remove_column :subjects, :tc_pam_1
	remove_column :subjects, :tc_pam_2
	remove_column :subjects, :tc_pam_3
	remove_column :subjects, :tc_pam_4
	remove_column :subjects, :tc_pam_5
	remove_column :subjects, :tc_pam_6
	remove_column :subjects, :tc_pam_7
	remove_column :subjects, :tc_pam_8
	remove_column :subjects, :tc_pam_9
	remove_column :subjects, :tc_pam_10
	remove_column :subjects, :tc_pam_11
	remove_column :subjects, :tc_pam_12
	remove_column :subjects, :tc_pam_13
	remove_column :subjects, :tc_spsi_1
	remove_column :subjects, :tc_spsi_2
	remove_column :subjects, :tc_spsi_3
	remove_column :subjects, :tc_spsi_4
	remove_column :subjects, :tc_spsi_5
	remove_column :subjects, :tc_spsi_6
	remove_column :subjects, :tc_spsi_7
	remove_column :subjects, :tc_spsi_8
	remove_column :subjects, :tc_spsi_9
	remove_column :subjects, :tc_spsi_10
	remove_column :subjects, :tc_spsi_11
	remove_column :subjects, :tc_spsi_12
	remove_column :subjects, :tc_spsi_13
	remove_column :subjects, :tc_spsi_14
	remove_column :subjects, :tc_spsi_15
	remove_column :subjects, :tc_spsi_16
	remove_column :subjects, :tc_spsi_17
	remove_column :subjects, :tc_spsi_18
	remove_column :subjects, :tc_spsi_19
	remove_column :subjects, :tc_spsi_20
	remove_column :subjects, :tc_spsi_21
	remove_column :subjects, :tc_spsi_22
	remove_column :subjects, :tc_spsi_23
	remove_column :subjects, :tc_spsi_24
	remove_column :subjects, :tc_spsi_25
	remove_column :subjects, :tc_soc_1
	remove_column :subjects, :tc_soc_2
	remove_column :subjects, :tc_soc_3
	remove_column :subjects, :tc_soc_4
	remove_column :subjects, :tc_soc_5
	remove_column :subjects, :tc_soc_6
	remove_column :subjects, :tc_pu_1
	remove_column :subjects, :tc_pu_2
	remove_column :subjects, :tc_pu_3
	remove_column :subjects, :tc_pu_4
	remove_column :subjects, :tc_cpg_1
	remove_column :subjects, :tc_cpg_2
	remove_column :subjects, :tc_cpg_3
	remove_column :subjects, :tc_cpg_4
	remove_column :subjects, :tc_cpg_5
	remove_column :subjects, :tc_cpg_6
	remove_column :subjects, :tc_cpg_7
	remove_column :subjects, :tc_comp_1
	remove_column :subjects, :tc_comp_2
	remove_column :subjects, :tc_comp_3
	remove_column :subjects, :tc_comp_4
	remove_column :subjects, :tc_comp_5_a1
	remove_column :subjects, :tc_comp_5_a2
	remove_column :subjects, :tc_comp_5_a3
	remove_column :subjects, :tc_comp_5_a4
	remove_column :subjects, :tc_comp_5_a5
	remove_column :subjects, :tc_comp_5_a6
	remove_column :subjects, :tc_comp_5_a7
	remove_column :subjects, :tc_comp_5b
	remove_column :subjects, :tc_comp_5c
	remove_column :subjects, :tc_comp_5c_level
	remove_column :subjects, :tc_comp_5c_type
	remove_column :subjects, :tc_mspss_1
	remove_column :subjects, :tc_mspss_2
	remove_column :subjects, :tc_mspss_3
	remove_column :subjects, :tc_mspss_4
	remove_column :subjects, :tc_mspss_5
	remove_column :subjects, :tc_mspss_6
	remove_column :subjects, :tc_mspss_7
	remove_column :subjects, :tc_mspss_8
	remove_column :subjects, :tc_mspss_9
	remove_column :subjects, :tc_mspss_10
	remove_column :subjects, :tc_mspss_11
	remove_column :subjects, :tc_mspss_12
	remove_column :subjects, :tc_audit_1
	remove_column :subjects, :tc_audit_2
	remove_column :subjects, :tc_audit_3
	remove_column :subjects, :tc_ptcs_1
	remove_column :subjects, :tc_ptcs_2
	remove_column :subjects, :tc_ptcs_3
	remove_column :subjects, :tc_ptcs_4
	remove_column :subjects, :tc_ptcs_5
	remove_column :subjects, :tc_ptcs_6
	remove_column :subjects, :tc_ptcs_7
	remove_column :subjects, :tc_ptcs_8
	remove_column :subjects, :tc_ptcs_9
	remove_column :subjects, :tc_ptcs_10
	remove_column :subjects, :tc_ptcs_11
	remove_column :subjects, :tc_ptcs_12
	remove_column :subjects, :tc_ptcs_13
	remove_column :subjects, :tc_ptcs_14
	remove_column :subjects, :tc_ptcs_15
	remove_column :subjects, :tc_ptcs_16
	remove_column :subjects, :tc_ptcs_17
	remove_column :subjects, :tc_ar_1
	remove_column :subjects, :tc_ar_2
	remove_column :subjects, :tc_ar_3
	remove_column :subjects, :tc_ar_4
	remove_column :subjects, :tc_ar_5
	remove_column :subjects, :tc_ar_6
	remove_column :subjects, :tc_ar_7
	remove_column :subjects, :tc_ar_8
	remove_column :subjects, :tc_ar_9
	remove_column :subjects, :tc_ar_9o
	remove_column :subjects, :tc_sat_1
	remove_column :subjects, :tc_sat_2
	remove_column :subjects, :tc_sat_3
	remove_column :subjects, :tc_sat_4
	remove_column :subjects, :tc_sat_5
	remove_column :subjects, :tc_sat_6
	remove_column :subjects, :tc_sat_7
	remove_column :subjects, :tc_sat_8
	remove_column :subjects, :tc_sat_9
	remove_column :subjects, :tc_sat_10
	remove_column :subjects, :tc_sat_11

	remove_column :subjects, :fu6month_smfa_1
	remove_column :subjects, :fu6month_smfa_2
	remove_column :subjects, :fu6month_smfa_3
	remove_column :subjects, :fu6month_smfa_4
	remove_column :subjects, :fu6month_smfa_5
	remove_column :subjects, :fu6month_smfa_6
	remove_column :subjects, :fu6month_smfa_7
	remove_column :subjects, :fu6month_smfa_8
	remove_column :subjects, :fu6month_smfa_9
	remove_column :subjects, :fu6month_smfa_10
	remove_column :subjects, :fu6month_smfa_11
	remove_column :subjects, :fu6month_smfa_12
	remove_column :subjects, :fu6month_smfa_13
	remove_column :subjects, :fu6month_smfa_14
	remove_column :subjects, :fu6month_smfa_15
	remove_column :subjects, :fu6month_smfa_16
	remove_column :subjects, :fu6month_smfa_17
	remove_column :subjects, :fu6month_smfa_18
	remove_column :subjects, :fu6month_smfa_19
	remove_column :subjects, :fu6month_smfa_20
	remove_column :subjects, :fu6month_smfa_21
	remove_column :subjects, :fu6month_smfa_22
	remove_column :subjects, :fu6month_smfa_23
	remove_column :subjects, :fu6month_smfa_24
	remove_column :subjects, :fu6month_smfa_25
	remove_column :subjects, :fu6month_smfa_26
	remove_column :subjects, :fu6month_smfa_27
	remove_column :subjects, :fu6month_smfa_28
	remove_column :subjects, :fu6month_smfa_29
	remove_column :subjects, :fu6month_smfa_30
	remove_column :subjects, :fu6month_smfa_31
	remove_column :subjects, :fu6month_smfa_32
	remove_column :subjects, :fu6month_smfa_33
	remove_column :subjects, :fu6month_smfa_34
	remove_column :subjects, :fu6month_smfa_35
	remove_column :subjects, :fu6month_smfa_36
	remove_column :subjects, :fu6month_smfa_37
	remove_column :subjects, :fu6month_smfa_38
	remove_column :subjects, :fu6month_smfa_39
	remove_column :subjects, :fu6month_smfa_40
	remove_column :subjects, :fu6month_smfa_41
	remove_column :subjects, :fu6month_smfa_42
	remove_column :subjects, :fu6month_smfa_43
	remove_column :subjects, :fu6month_smfa_44
	remove_column :subjects, :fu6month_smfa_45
	remove_column :subjects, :fu6month_smfa_46
	remove_column :subjects, :fu6month_phq_1
	remove_column :subjects, :fu6month_phq_2
	remove_column :subjects, :fu6month_phq_3
	remove_column :subjects, :fu6month_phq_4
	remove_column :subjects, :fu6month_phq_5
	remove_column :subjects, :fu6month_phq_6
	remove_column :subjects, :fu6month_phq_7
	remove_column :subjects, :fu6month_phq_8
	remove_column :subjects, :fu6month_phq_9
	remove_column :subjects, :fu6month_phq_10
	remove_column :subjects, :fu6month_whoqol_1
	remove_column :subjects, :fu6month_whoqol_2
	remove_column :subjects, :fu6month_panas_1
	remove_column :subjects, :fu6month_panas_2
	remove_column :subjects, :fu6month_panas_3
	remove_column :subjects, :fu6month_panas_4
	remove_column :subjects, :fu6month_panas_5
	remove_column :subjects, :fu6month_panas_6
	remove_column :subjects, :fu6month_panas_7
	remove_column :subjects, :fu6month_panas_8
	remove_column :subjects, :fu6month_panas_9
	remove_column :subjects, :fu6month_panas_10
	remove_column :subjects, :fu6month_panas_11
	remove_column :subjects, :fu6month_panas_12
	remove_column :subjects, :fu6month_panas_13
	remove_column :subjects, :fu6month_panas_14
	remove_column :subjects, :fu6month_panas_15
	remove_column :subjects, :fu6month_panas_16
	remove_column :subjects, :fu6month_panas_17
	remove_column :subjects, :fu6month_panas_18
	remove_column :subjects, :fu6month_panas_19
	remove_column :subjects, :fu6month_panas_20
	remove_column :subjects, :fu6month_mses_1
	remove_column :subjects, :fu6month_mses_2
	remove_column :subjects, :fu6month_mses_3
	remove_column :subjects, :fu6month_mses_4
	remove_column :subjects, :fu6month_mses_5
	remove_column :subjects, :fu6month_mses_6
	remove_column :subjects, :fu6month_mses_7
	remove_column :subjects, :fu6month_mses_8
	remove_column :subjects, :fu6month_mses_9
	remove_column :subjects, :fu6month_pam_1
	remove_column :subjects, :fu6month_pam_2
	remove_column :subjects, :fu6month_pam_3
	remove_column :subjects, :fu6month_pam_4
	remove_column :subjects, :fu6month_pam_5
	remove_column :subjects, :fu6month_pam_6
	remove_column :subjects, :fu6month_pam_7
	remove_column :subjects, :fu6month_pam_8
	remove_column :subjects, :fu6month_pam_9
	remove_column :subjects, :fu6month_pam_10
	remove_column :subjects, :fu6month_pam_11
	remove_column :subjects, :fu6month_pam_12
	remove_column :subjects, :fu6month_pam_13
	remove_column :subjects, :fu6month_spsi_1
	remove_column :subjects, :fu6month_spsi_2
	remove_column :subjects, :fu6month_spsi_3
	remove_column :subjects, :fu6month_spsi_4
	remove_column :subjects, :fu6month_spsi_5
	remove_column :subjects, :fu6month_spsi_6
	remove_column :subjects, :fu6month_spsi_7
	remove_column :subjects, :fu6month_spsi_8
	remove_column :subjects, :fu6month_spsi_9
	remove_column :subjects, :fu6month_spsi_10
	remove_column :subjects, :fu6month_spsi_11
	remove_column :subjects, :fu6month_spsi_12
	remove_column :subjects, :fu6month_spsi_13
	remove_column :subjects, :fu6month_spsi_14
	remove_column :subjects, :fu6month_spsi_15
	remove_column :subjects, :fu6month_spsi_16
	remove_column :subjects, :fu6month_spsi_17
	remove_column :subjects, :fu6month_spsi_18
	remove_column :subjects, :fu6month_spsi_19
	remove_column :subjects, :fu6month_spsi_20
	remove_column :subjects, :fu6month_spsi_21
	remove_column :subjects, :fu6month_spsi_22
	remove_column :subjects, :fu6month_spsi_23
	remove_column :subjects, :fu6month_spsi_24
	remove_column :subjects, :fu6month_spsi_25
	remove_column :subjects, :fu6month_soc_1
	remove_column :subjects, :fu6month_soc_2
	remove_column :subjects, :fu6month_soc_3
	remove_column :subjects, :fu6month_soc_4
	remove_column :subjects, :fu6month_soc_5
	remove_column :subjects, :fu6month_soc_6
	remove_column :subjects, :fu6month_pu_1
	remove_column :subjects, :fu6month_pu_2
	remove_column :subjects, :fu6month_pu_3
	remove_column :subjects, :fu6month_pu_4
	remove_column :subjects, :fu6month_cpg_1
	remove_column :subjects, :fu6month_cpg_2
	remove_column :subjects, :fu6month_cpg_3
	remove_column :subjects, :fu6month_cpg_4
	remove_column :subjects, :fu6month_cpg_5
	remove_column :subjects, :fu6month_cpg_6
	remove_column :subjects, :fu6month_cpg_7
	remove_column :subjects, :fu6month_comp_1
	remove_column :subjects, :fu6month_comp_2
	remove_column :subjects, :fu6month_comp_3
	remove_column :subjects, :fu6month_comp_4
	remove_column :subjects, :fu6month_comp_5_a1
	remove_column :subjects, :fu6month_comp_5_a2
	remove_column :subjects, :fu6month_comp_5_a3
	remove_column :subjects, :fu6month_comp_5_a4
	remove_column :subjects, :fu6month_comp_5_a5
	remove_column :subjects, :fu6month_comp_5_a6
	remove_column :subjects, :fu6month_comp_5_a7
	remove_column :subjects, :fu6month_comp_5b
	remove_column :subjects, :fu6month_comp_5c
	remove_column :subjects, :fu6month_comp_5c_level
	remove_column :subjects, :fu6month_comp_5c_type
	remove_column :subjects, :fu6month_mspss_1
	remove_column :subjects, :fu6month_mspss_2
	remove_column :subjects, :fu6month_mspss_3
	remove_column :subjects, :fu6month_mspss_4
	remove_column :subjects, :fu6month_mspss_5
	remove_column :subjects, :fu6month_mspss_6
	remove_column :subjects, :fu6month_mspss_7
	remove_column :subjects, :fu6month_mspss_8
	remove_column :subjects, :fu6month_mspss_9
	remove_column :subjects, :fu6month_mspss_10
	remove_column :subjects, :fu6month_mspss_11
	remove_column :subjects, :fu6month_mspss_12
	remove_column :subjects, :fu6month_audit_1
	remove_column :subjects, :fu6month_audit_2
	remove_column :subjects, :fu6month_audit_3

	remove_column :subjects, :fu3week_fuq_1
	remove_column :subjects, :fu3week_fuq_2
	remove_column :subjects, :fu3week_fuq_2a
	remove_column :subjects, :fu3week_fuq_3
	remove_column :subjects, :fu3week_fuq_3a
	remove_column :subjects, :fu3week_fuq_4
	remove_column :subjects, :fu3week_fuq_4a_level
	remove_column :subjects, :fu3week_fuq_4a_type
	remove_column :subjects, :fu3week_fuq_4b
	remove_column :subjects, :fu3week_fuq_5
	remove_column :subjects, :fu3week_fuq_5a
	remove_column :subjects, :fu3week_fuq_6
	remove_column :subjects, :fu3week_fuq_6a
	remove_column :subjects, :fu3week_fuq_7
	remove_column :subjects, :fu6week_fuq_1
	remove_column :subjects, :fu6week_fuq_2
	remove_column :subjects, :fu6week_fuq_2a
	remove_column :subjects, :fu6week_fuq_3
	remove_column :subjects, :fu6week_fuq_3a
	remove_column :subjects, :fu6week_fuq_4
	remove_column :subjects, :fu6week_fuq_4a_level
	remove_column :subjects, :fu6week_fuq_4a_type
	remove_column :subjects, :fu6week_fuq_4b
	remove_column :subjects, :fu6week_fuq_5
	remove_column :subjects, :fu6week_fuq_5a
	remove_column :subjects, :fu6week_fuq_6
	remove_column :subjects, :fu6week_fuq_6a
	remove_column :subjects, :fu6week_fuq_7
	remove_column :subjects, :fu18week_fuq_1
	remove_column :subjects, :fu18week_fuq_2
	remove_column :subjects, :fu18week_fuq_2a
	remove_column :subjects, :fu18week_fuq_3
	remove_column :subjects, :fu18week_fuq_3a
	remove_column :subjects, :fu18week_fuq_4
	remove_column :subjects, :fu18week_fuq_4a_level
	remove_column :subjects, :fu18week_fuq_4a_type
	remove_column :subjects, :fu18week_fuq_4b
	remove_column :subjects, :fu18week_fuq_5
	remove_column :subjects, :fu18week_fuq_5a
	remove_column :subjects, :fu18week_fuq_6
	remove_column :subjects, :fu18week_fuq_6a
	remove_column :subjects, :fu18week_fuq_7
	remove_column :subjects, :fu1year_fuq_1
	remove_column :subjects, :fu1year_fuq_2
	remove_column :subjects, :fu1year_fuq_2a
	remove_column :subjects, :fu1year_fuq_3
	remove_column :subjects, :fu1year_fuq_3a
	remove_column :subjects, :fu1year_fuq_4
	remove_column :subjects, :fu1year_fuq_4a_level
	remove_column :subjects, :fu1year_fuq_4a_type
	remove_column :subjects, :fu1year_fuq_4b
	remove_column :subjects, :fu1year_fuq_5
	remove_column :subjects, :fu1year_fuq_5a
	remove_column :subjects, :fu1year_fuq_6
	remove_column :subjects, :fu1year_fuq_6a
	remove_column :subjects, :fu1year_fuq_7
  end

  def down
  end
end
