class CreateBaselines < ActiveRecord::Migration
  def change
    create_table :baselines do |t|
        t.integer :subject_id
        t.belongs_to :subject
        t.integer :baseline, :base_smfa_1, :integer
		t.integer :baseline, :base_smfa_2, :integer
		t.integer :baseline, :base_smfa_3, :integer
		t.integer :baseline, :base_smfa_4, :integer
		t.integer :baseline, :base_smfa_5, :integer
		t.integer :baseline, :base_smfa_6, :integer
		t.integer :baseline, :base_smfa_7, :integer
		t.integer :baseline, :base_smfa_8, :integer
		t.integer :baseline, :base_smfa_9, :integer
		t.integer :baseline, :base_smfa_10, :integer
		t.integer :baseline, :base_smfa_11, :integer
		t.integer :baseline, :base_smfa_12, :integer
		t.integer :baseline, :base_smfa_13, :integer
		t.integer :baseline, :base_smfa_14, :integer
		t.integer :baseline, :base_smfa_15, :integer
		t.integer :baseline, :base_smfa_16, :integer
		t.integer :baseline, :base_smfa_17, :integer
		t.integer :baseline, :base_smfa_18, :integer
		t.integer :baseline, :base_smfa_19, :integer
		t.integer :baseline, :base_smfa_20, :integer
		t.integer :baseline, :base_smfa_21, :integer
		t.integer :baseline, :base_smfa_22, :integer
		t.integer :baseline, :base_smfa_23, :integer
		t.integer :baseline, :base_smfa_24, :integer
		t.integer :baseline, :base_smfa_25, :integer
		t.integer :baseline, :base_smfa_26, :integer
		t.integer :baseline, :base_smfa_27, :integer
		t.integer :baseline, :base_smfa_28, :integer
		t.integer :baseline, :base_smfa_29, :integer
		t.integer :baseline, :base_smfa_30, :integer
		t.integer :baseline, :base_smfa_31, :integer
		t.integer :baseline, :base_smfa_32, :integer
		t.integer :baseline, :base_smfa_33, :integer
		t.integer :baseline, :base_smfa_34, :integer
		t.integer :baseline, :base_smfa_35, :integer
		t.integer :baseline, :base_smfa_36, :integer
		t.integer :baseline, :base_smfa_37, :integer
		t.integer :baseline, :base_smfa_38, :integer
		t.integer :baseline, :base_smfa_39, :integer
		t.integer :baseline, :base_smfa_40, :integer
		t.integer :baseline, :base_smfa_41, :integer
		t.integer :baseline, :base_smfa_42, :integer
		t.integer :baseline, :base_smfa_43, :integer
		t.integer :baseline, :base_smfa_44, :integer
		t.integer :baseline, :base_smfa_45, :integer
		t.integer :baseline, :base_smfa_46, :integer
		t.integer :baseline, :base_phq_1, :integer
		t.integer :baseline, :base_phq_2, :integer
		t.integer :baseline, :base_phq_3, :integer
		t.integer :baseline, :base_phq_4, :integer
		t.integer :baseline, :base_phq_5, :integer
		t.integer :baseline, :base_phq_6, :integer
		t.integer :baseline, :base_phq_7, :integer
		t.integer :baseline, :base_phq_8, :integer
		t.integer :baseline, :base_phq_9, :integer
		t.integer :baseline, :base_phq_10, :integer
		t.integer :baseline, :base_whoqol_1, :integer
		t.integer :baseline, :base_whoqol_2, :integer
		t.integer :baseline, :base_panas_1, :integer
		t.integer :baseline, :base_panas_2, :integer
		t.integer :baseline, :base_panas_3, :integer
		t.integer :baseline, :base_panas_4, :integer
		t.integer :baseline, :base_panas_5, :integer
		t.integer :baseline, :base_panas_6, :integer
		t.integer :baseline, :base_panas_7, :integer
		t.integer :baseline, :base_panas_8, :integer
		t.integer :baseline, :base_panas_9, :integer
		t.integer :baseline, :base_panas_10, :integer
		t.integer :baseline, :base_panas_11, :integer
		t.integer :baseline, :base_panas_12, :integer
		t.integer :baseline, :base_panas_13, :integer
		t.integer :baseline, :base_panas_14, :integer
		t.integer :baseline, :base_panas_15, :integer
		t.integer :baseline, :base_panas_16, :integer
		t.integer :baseline, :base_panas_17, :integer
		t.integer :baseline, :base_panas_18, :integer
		t.integer :baseline, :base_panas_19, :integer
		t.integer :baseline, :base_panas_20, :integer
		t.integer :baseline, :base_mses_1, :integer
		t.integer :baseline, :base_mses_2, :integer
		t.integer :baseline, :base_mses_3, :integer
		t.integer :baseline, :base_mses_4, :integer
		t.integer :baseline, :base_mses_5, :integer
		t.integer :baseline, :base_mses_6, :integer
		t.integer :baseline, :base_mses_7, :integer
		t.integer :baseline, :base_mses_8, :integer
		t.integer :baseline, :base_mses_9, :integer
		t.integer :baseline, :base_pam_1, :integer
		t.integer :baseline, :base_pam_2, :integer
		t.integer :baseline, :base_pam_3, :integer
		t.integer :baseline, :base_pam_4, :integer
		t.integer :baseline, :base_pam_5, :integer
		t.integer :baseline, :base_pam_6, :integer
		t.integer :baseline, :base_pam_7, :integer
		t.integer :baseline, :base_pam_8, :integer
		t.integer :baseline, :base_pam_9, :integer
		t.integer :baseline, :base_pam_10, :integer
		t.integer :baseline, :base_pam_11, :integer
		t.integer :baseline, :base_pam_12, :integer
		t.integer :baseline, :base_pam_13, :integer
		t.integer :baseline, :base_spsi_1, :integer
		t.integer :baseline, :base_spsi_2, :integer
		t.integer :baseline, :base_spsi_3, :integer
		t.integer :baseline, :base_spsi_4, :integer
		t.integer :baseline, :base_spsi_5, :integer
		t.integer :baseline, :base_spsi_6, :integer
		t.integer :baseline, :base_spsi_7, :integer
		t.integer :baseline, :base_spsi_8, :integer
		t.integer :baseline, :base_spsi_9, :integer
		t.integer :baseline, :base_spsi_10, :integer
		t.integer :baseline, :base_spsi_11, :integer
		t.integer :baseline, :base_spsi_12, :integer
		t.integer :baseline, :base_spsi_13, :integer
		t.integer :baseline, :base_spsi_14, :integer
		t.integer :baseline, :base_spsi_15, :integer
		t.integer :baseline, :base_spsi_16, :integer
		t.integer :baseline, :base_spsi_17, :integer
		t.integer :baseline, :base_spsi_18, :integer
		t.integer :baseline, :base_spsi_19, :integer
		t.integer :baseline, :base_spsi_20, :integer
		t.integer :baseline, :base_spsi_21, :integer
		t.integer :baseline, :base_spsi_22, :integer
		t.integer :baseline, :base_spsi_23, :integer
		t.integer :baseline, :base_spsi_24, :integer
		t.integer :baseline, :base_spsi_25, :integer
		t.integer :baseline, :base_soc_1, :integer
		t.integer :baseline, :base_soc_2, :integer
		t.integer :baseline, :base_soc_3, :integer
		t.integer :baseline, :base_soc_4, :integer
		t.integer :baseline, :base_soc_5, :integer
		t.integer :baseline, :base_soc_6, :integer
		t.integer :baseline, :base_pu_1, :integer
		t.integer :baseline, :base_pu_2, :integer
		t.integer :baseline, :base_pu_3, :integer
		t.integer :baseline, :base_pu_4, :integer
		t.integer :baseline, :base_rbans_t1_1, :integer
		t.integer :baseline, :base_rbans_t1_2, :integer
		t.integer :baseline, :base_rbans_t1_3, :integer
		t.integer :baseline, :base_rbans_t1_4, :integer
		t.integer :baseline, :base_rbans_t1_5, :integer
		t.integer :baseline, :base_rbans_t1_6, :integer
		t.integer :baseline, :base_rbans_t1_7, :integer
		t.integer :baseline, :base_rbans_t1_8, :integer
		t.integer :baseline, :base_rbans_t1_9, :integer
		t.integer :baseline, :base_rbans_t1_10, :integer    
		t.integer :baseline, :base_rbans_t2_1, :integer
		t.integer :baseline, :base_rbans_t2_2, :integer
		t.integer :baseline, :base_rbans_t2_3, :integer
		t.integer :baseline, :base_rbans_t2_4, :integer
		t.integer :baseline, :base_rbans_t2_5, :integer
		t.integer :baseline, :base_rbans_t2_6, :integer
		t.integer :baseline, :base_rbans_t2_7, :integer
		t.integer :baseline, :base_rbans_t2_8, :integer
		t.integer :baseline, :base_rbans_t2_9, :integer
		t.integer :baseline, :base_rbans_t2_10, :integer
		t.integer :baseline, :base_rbans_t3_1, :integer
		t.integer :baseline, :base_rbans_t3_2, :integer
		t.integer :baseline, :base_rbans_t3_3, :integer
		t.integer :baseline, :base_rbans_t3_4, :integer
		t.integer :baseline, :base_rbans_t3_5, :integer
		t.integer :baseline, :base_rbans_t3_6, :integer
		t.integer :baseline, :base_rbans_t3_7, :integer
		t.integer :baseline, :base_rbans_t3_8, :integer
		t.integer :baseline, :base_rbans_t3_9, :integer
		t.integer :baseline, :base_rbans_t3_10, :integer
		t.integer :baseline, :base_rbans_t4_1, :integer
		t.integer :baseline, :base_rbans_t4_2, :integer
		t.integer :baseline, :base_rbans_t4_3, :integer
		t.integer :baseline, :base_rbans_t4_4, :integer
		t.integer :baseline, :base_rbans_t4_5, :integer
		t.integer :baseline, :base_rbans_t4_6, :integer
		t.integer :baseline, :base_rbans_t4_7, :integer
		t.integer :baseline, :base_rbans_t4_8, :integer
		t.integer :baseline, :base_rbans_t4_9, :integer
		t.integer :baseline, :base_rbans_t4_10, :integer
		t.integer :baseline, :base_wais_a_1_t1, :integer
		t.integer :baseline, :base_wais_a_1_t2, :integer
		t.integer :baseline, :base_wais_a_2_t1, :integer
		t.integer :baseline, :base_wais_a_2_t2, :integer
		t.integer :baseline, :base_wais_a_3_t1, :integer
		t.integer :baseline, :base_wais_a_3_t2, :integer
		t.integer :baseline, :base_wais_a_4_t1, :integer
		t.integer :baseline, :base_wais_a_4_t2, :integer
		t.integer :baseline, :base_wais_a_5_t1, :integer
		t.integer :baseline, :base_wais_a_5_t2, :integer
		t.integer :baseline, :base_wais_a_6_t1, :integer
		t.integer :baseline, :base_wais_a_6_t2, :integer
		t.integer :baseline, :base_wais_a_7_t1, :integer
		t.integer :baseline, :base_wais_a_7_t2, :integer
		t.integer :baseline, :base_wais_a_8_t1, :integer
		t.integer :baseline, :base_wais_a_8_t2, :integer    
		t.integer :baseline, :base_wais_b_1_t1, :integer
		t.integer :baseline, :base_wais_b_1_t2, :integer
		t.integer :baseline, :base_wais_b_2_t1, :integer
		t.integer :baseline, :base_wais_b_2_t2, :integer
		t.integer :baseline, :base_wais_b_3_t1, :integer
		t.integer :baseline, :base_wais_b_3_t2, :integer
		t.integer :baseline, :base_wais_b_4_t1, :integer
		t.integer :baseline, :base_wais_b_4_t2, :integer
		t.integer :baseline, :base_wais_b_5_t1, :integer
		t.integer :baseline, :base_wais_b_5_t2, :integer
		t.integer :baseline, :base_wais_b_6_t1, :integer
		t.integer :baseline, :base_wais_b_6_t2, :integer
		t.integer :baseline, :base_wais_b_7_t1, :integer
		t.integer :baseline, :base_wais_b_7_t2, :integer
		t.integer :baseline, :base_rbans_re_1, :integer
		t.integer :baseline, :base_rbans_re_2, :integer
		t.integer :baseline, :base_rbans_re_3, :integer
		t.integer :baseline, :base_rbans_re_4, :integer
		t.integer :baseline, :base_rbans_re_5, :integer
		t.integer :baseline, :base_rbans_re_6, :integer
		t.integer :baseline, :base_rbans_re_7, :integer
		t.integer :baseline, :base_rbans_re_8, :integer
		t.integer :baseline, :base_rbans_re_9, :integer
		t.integer :baseline, :base_rbans_re_10, :integer
		t.integer :baseline, :base_cq_1a, :integer
		t.integer :baseline, :base_cq_1b, :integer
		t.integer :baseline, :base_cq_1b_side, :integer
		t.integer :baseline, :base_cq_1c, :integer
		t.integer :baseline, :base_cq_1d, :integer
		t.integer :baseline, :base_cq_1d_joint, :integer
		t.integer :baseline, :base_cq_1e, :integer
		t.integer :baseline, :base_cq_1f, :integer
		t.integer :baseline, :base_cq_1g, :integer
		t.integer :baseline, :base_cq_2, :integer
		t.integer :baseline, :base_cq_2a, :integer
		t.integer :baseline, :base_cq_3a, :integer
		t.integer :baseline, :base_cq_3b, :integer
		t.integer :baseline, :base_cq_3c, :integer
		t.integer :baseline, :base_cq_3d, :integer
		t.integer :baseline, :base_cq_4, :integer
		t.integer :baseline, :base_cq_5, :integer
		t.integer :baseline, :base_cq_6, :integer
		t.integer :baseline, :base_cq_7, :integer
		t.integer :baseline, :base_cq_8, :integer
		t.integer :baseline, :base_cq_9, :integer
		t.integer :baseline, :base_cq_10_a1, :integer
		t.integer :baseline, :base_cq_10_a2, :integer
		t.integer :baseline, :base_cq_10_a3, :integer
		t.integer :baseline, :base_cq_10_a4, :integer
		t.integer :baseline, :base_cq_10_a5, :integer
		t.integer :baseline, :base_cq_10_a6, :integer
		t.integer :baseline, :base_cq_10_a7, :integer
		t.integer :baseline, :base_cq_10_b, :integer
		t.integer :baseline, :base_cq_10_c, :integer
		t.integer :baseline, :base_cq_10_c_level, :integer
		t.integer :baseline, :base_cq_10_c_type, :integer
		t.integer :baseline, :base_cpg_1, :integer
		t.integer :baseline, :base_cpg_2, :integer
		t.integer :baseline, :base_cpg_3, :integer
		t.integer :baseline, :base_cpg_4, :integer
		t.integer :baseline, :base_cpg_5, :integer
		t.integer :baseline, :base_cpg_6, :integer
		t.integer :baseline, :base_cpg_7, :integer
		t.integer :baseline, :base_comp1, :integer
		t.integer :baseline, :base_comp2, :integer
		t.integer :baseline, :base_comp3, :integer
		t.integer :baseline, :base_comp4, :integer
		t.integer :baseline, :base_comp5_a1, :integer
		t.integer :baseline, :base_comp5_a2, :integer
		t.integer :baseline, :base_comp5_a3, :integer
		t.integer :baseline, :base_comp5_a4, :integer
		t.integer :baseline, :base_comp5_a5, :integer
		t.integer :baseline, :base_comp5_a6, :integer
		t.integer :baseline, :base_comp5_a7, :integer
		t.integer :baseline, :base_comp5b, :integer
		t.integer :baseline, :base_comp5c, :integer
		t.integer :baseline, :base_comp5c_level, :integer
		t.integer :baseline, :base_comp5c_type, :integer
		t.integer :baseline, :base_mspss_1, :integer
		t.integer :baseline, :base_mspss_2, :integer
		t.integer :baseline, :base_mspss_3, :integer
		t.integer :baseline, :base_mspss_4, :integer
		t.integer :baseline, :base_mspss_5, :integer
		t.integer :baseline, :base_mspss_6, :integer
		t.integer :baseline, :base_mspss_7, :integer
		t.integer :baseline, :base_mspss_8, :integer
		t.integer :baseline, :base_mspss_9, :integer
		t.integer :baseline, :base_mspss_10, :integer
		t.integer :baseline, :base_mspss_11, :integer
		t.integer :baseline, :base_mspss_12, :integer
		t.integer :baseline, :base_audit_1, :integer
		t.integer :baseline, :base_audit_2, :integer
		t.integer :baseline, :base_audit_3, :integer

      	t.timestamps
    end
    add_index :baselines, :subject_id
  end

end
